# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sopt22_seminar4' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'Kingfisher'

  # Pods for Sopt22_seminar4

end
